### ISSUE TITLE
[BUG 🪲] List of objects are corrupted !!

### ISSUE THREAD

**Issue by Clorabase-databases** [Clorabase/CloremDB#5]
Java isn't deserializing or serializing a complete list of custom objects. Items are missing when fetched.

⚠️ **_This is an unexpected and critical failure of the database_, there are possibility that if this bug is not fixed, then the project will be shut down**

**Comment by ErrorxCode** [comment]
database [rewritten](https://github.com/Clorabase/CloremDB/releases/tag/3.0)
